operators:
  camelk-operator:
    enabled: true
    namespace:
      name: camelktest
    subscription:
      channel: 1.10.x
      approval: Manual
      operatorName: red-hat-camel-k
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: red-hat-camel-k-operator.v1.10.6

helper-status-checker:
      enabled: true 
      approver: true

      # use the value of the currentCSV (packagemanifest) but WITHOUT the version !!
      operatorName: red-hat-camel-k

      # where operator is installed
      namespace:
        name: camelktest

      serviceAccount: 
        create: true
        name: "status-checker" 
